### ISSUE TITLE
Reorganize build and download section

### ISSUE THREAD

**Issue by eselmeister** [eclipse/swtchart#126]
The build and download section shall be reorganized. Continuous build bundles shall be stored in:

- download.eclipse.org/swtchart/integration

All official and stable releases shall be stored in:

- download.eclipse.org/swtchart/releases

**Comment by laeubi** [comment]
For releases I think there must be changed the following things:

1. automatic nightly builds should be disabled (there is no real need for it)
2. automatic builds on scm change should be disabled (so builds are only triggered, manuall)
3. each build should deploy in an own folder (e.g using the build number or a tag)
4. all individual builds should be aggregated inside a composite repository residing in the root of this "build-folder"

for example structure would be as follows:
base path: /.../release/0.12.x
build folders: /.../release/0.12.x/1
/.../release/0.12.x/2
/.../release/0.12.x/... and so on

repository path /.../release/0.12.x/repository contains a composite.xml listing all the individual build folder.
