### ISSUE TITLE
Release-Repository is not stable

### ISSUE THREAD

**Issue by laeubi** [eclipse/swtchart#127]
Currently the release repository uses the "continious-deployment" part of the swt-chart Jenkins file. This leads to the problem that the version of the release artifacts change every day:

For releases I think there must be changed the following things:

    automatic nightly builds should be disabled (there is no real need for it)
    automatic builds on scm change should be disabled (so builds are only triggered, manuall)
    each build should deploy in an own folder (e.g using the build number or a tag)
    all individual builds should be aggregated inside a composite repository residing in the root of this "build-folder"

for example structure would be as follows:
base path: /.../release/0.12.x
build folders: /.../release/0.12.x/1
/.../release/0.12.x/2
/.../release/0.12.x/... and so on

repository path /.../release/0.12.x/repository contains a composite.xml listing all the individual build folder.

**Comment by laeubi** [comment]
@eselmeister imo the current git structure is not complete to have a stable release, I would have expected at least the following items:

- a branch named 0.12.x (there is only a REL-0.12.0 one)
- a tag named 0.12.0 (this would then also show up under the github releases)

Then there will be appropriate build for building the latest 0.12.x / bugfix branch, after the build is done the content could then be copied to a new "release" location and would stay constant over time.

**Comment by eselmeister** [comment]
The Jenkins build files have been adjusted. The "https://download.eclipse.org/swtchart" section has been also improved:

- integration: contains the continuous integration builds for each branch
- releases: contains the stable official releases

Official URLs for Eclipse SWTChart downloads and fragments are listed here:

https://projects.eclipse.org/projects/science.swtchart/downloads
https://github.com/eclipse/swtchart/releases

**Comment by laeubi** [comment]
https://github.com/eclipse/swtchart/blob/REL-0.12.0/Jenkinsfile still rebuilds on each change and each day, also I don't see anything that enforces stable build qualifiers based on tagged version so the build will produce still a new version each day leading to a constantly changing release-repository.

**Comment by eselmeister** [comment]
It's on purpose to ensure that the build keeps on being green. That's why it's in the "integration" area. As mentioned, the stable release is available here:

https://download.eclipse.org/swtchart/releases/0.12.0/repository

**Comment by laeubi** [comment]
I see so one has to copy from integration area to  release are once the release is ready manually?

**Comment by eselmeister** [comment]
Yes, that's correct. The project lead is responsible to do this, as he/she keeps track of the release status and ensures that all paperwork is done and that the review has been concluded successfully.

In this case, I have copied the stable release to the release directory. The branch stays in the integration build process to ensure that bugfix release an be created. If a bugfix release is required for the version 0.12.0, one could checkout the branch REL-0.12.0 and create a bugfix release branch e.g. REL-0.12.1, apply the changes, do the paperwork ... and so on.
