### ISSUE TITLE
Bar not visible if y data Coordinate is not within axis range

### ISSUE THREAD

**Issue by himanshu-balasamanta** [eclipse/swtchart#133]
The Bar with intensity 1.0E3
![zout](https://user-images.githubusercontent.com/44469499/78161732-8b8bca00-7463-11ea-9ea1-942724238863.png)
when zoomed in becomes
![zin](https://user-images.githubusercontent.com/44469499/78161912-c55cd080-7463-11ea-871d-15819b848e0e.png)

**Comment by eselmeister** [comment]
@Himanshu-Balasamanta You could also use keywords in the commits to automatically close related issues, e.g: "Fixed #133 - bar series is visible now"

**Comment by eselmeister** [comment]
https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords
