### ISSUE TITLE
Interactive Legend

### ISSUE THREAD

**Issue by eselmeister** [eclipse/swtchart#137]
People have requested to get an interactive legend. This should list:

- visibility of the series
- color
- series id
- series description

Except of series id, values shall be editable/adjustable.

**Comment by buchen** [comment]
One important thing should be that a) it is possible to add custom actions and b) one gets events in order to react to changes that have been done to the data series via the legend.

On the legend, I am allowing the user to
* remove a series,
* change the color,
* sort all series by name,
* change line style,
* change fill area,
* and re-ordering (move up, move down).

**Comment by eselmeister** [comment]
@buchen Yep, that's planned. It is also planned to place an embedded legend via the interactive legend editor. This could be achieved by using a "ICustomPaintListener" implementation.

![Bildschirmfoto von 2020-04-06 08-43-07](https://user-images.githubusercontent.com/686671/78530231-92a83480-77e3-11ea-8575-f371b5853a8d.png)

**Comment by eselmeister** [comment]
The screenshot shows the current tests I'm developing to enable such functionality in SWTChart. The scrollable chart is extended by a SashForm. By default, the extended legend part shall be invisible. It can be activated/deactivated by using a button or menu item to show/hide it.

**Comment by eselmeister** [comment]
![Bildschirmfoto von 2020-04-06 17-59-17](https://user-images.githubusercontent.com/686671/78579185-d2e1d400-7830-11ea-9ab8-8a2b867b3c88.png)

**Comment by eselmeister** [comment]
The enhanced legend is ready now:

![Bildschirmfoto von 2020-04-07 16-32-51](https://user-images.githubusercontent.com/686671/78682150-ebfc8a80-78ed-11ea-91a7-96f0c1958999.png)
![Bildschirmfoto von 2020-04-07 16-32-59](https://user-images.githubusercontent.com/686671/78682153-ed2db780-78ed-11ea-9d84-cfc3fc42f2eb.png)
![Bildschirmfoto von 2020-04-07 16-33-03](https://user-images.githubusercontent.com/686671/78682154-edc64e00-78ed-11ea-80a0-a66800d83e10.png)
![Bildschirmfoto von 2020-04-07 16-33-52](https://user-images.githubusercontent.com/686671/78682157-edc64e00-78ed-11ea-8fd0-1c80afa91f2a.png)
![Bildschirmfoto von 2020-04-07 16-34-00](https://user-images.githubusercontent.com/686671/78682158-ee5ee480-78ed-11ea-82c1-b25a6d550850.png)
![Bildschirmfoto von 2020-04-07 16-34-09](https://user-images.githubusercontent.com/686671/78682161-eef77b00-78ed-11ea-8da3-56783b2ab077.png)
![Bildschirmfoto von 2020-04-07 16-34-27](https://user-images.githubusercontent.com/686671/78682163-ef901180-78ed-11ea-8ec6-d161fdefdff4.png)
![Bildschirmfoto von 2020-04-07 16-34-38](https://user-images.githubusercontent.com/686671/78682165-f028a800-78ed-11ea-9879-8a7c8813dac0.png)

**Comment by eselmeister** [comment]
The ISeriesSettings instance itself is tracked. This allows to add additional values to the legend editor list. Probably, a ISeriesSettings dialog could be created (like the color editor) to show all settings, so that only the most important are displayed in the list.

**Comment by eselmeister** [comment]
@fbuloup Would you like to add the new text fields into the translation service?
