### ISSUE TITLE
new buffer feature breaks on OSX

### ISSUE THREAD

**Issue by lorenzgerber** [eclipse/swtchart#150]
When using swtchart in openchrom/chemclipse (https://github.com/eclipse/chemclipse) on OSX, the drawing (eg chromatogram) disappears when clicking into the graph for selection/zooming. After releasing the mouse button, the drawing will appear again.

**Comment by eselmeister** [comment]
@yashTEF The buffer works fine, but there seems to be an issue with macOS. I could imagine, that this is related to the following issue under macOS:
https://github.com/eclipse/swtchart/issues/86

**Comment by yashTEF** [comment]
I looked up the mentioned issue,Seems like a problem in the 
`getImageData()` method of the plot area.However I compared the implementation to the one in ImageSupplier and the only difference I can find is that plot area is not redrawn before converting into image data.
Example in ImageSupplier-
`baseChart.redraw()`
`baseChart.update()`

**Comment by buchen** [comment]
@yashTEF - how do I test this with SWTChart repository? (e.g. not dowloading chemclipse) I'd love to continue to use SWTChart on macOS

**Comment by eselmeister** [comment]
@buchen You can start SWTChart directly from the source code, either run it as an Eclipse application or use the DemoChart plain java application.

![Bildschirmfoto von 2020-04-15 07-42-27](https://user-images.githubusercontent.com/686671/79302544-f79f1100-7eec-11ea-9e7f-4ebab379368b.png)

![Bildschirmfoto von 2020-04-15 07-43-15](https://user-images.githubusercontent.com/686671/79302548-fbcb2e80-7eec-11ea-851f-32916efcb1b1.png)

**Comment by eselmeister** [comment]
To test the buffered selection, it needs to be enabled via the IChartSettings:

```
IChartSettings chartSettings = scrollableChart.getChartSettings();
chartSettings.setBufferSelection(true);
scrollableChart.applySettings(chartSettings);
```

**Comment by buchen** [comment]
I can confirm there is a problem if I a) activate the buffer selection and b) remove the test for macOS in the ChartSetting class. I can also confirm that it works if I leave the check for the macOS active.

I have made three screenshots:
* First before clicking
* Second after clicking and holding the mouse, but before *moving* the mouse
* Third after moving the mouse while holding the button clicked.


To me it looks like the buffering has problems with the retina solution. If you have a look at the second image, you notice that the grid is (almost) twice as big and the text is much bigger? Maybe the buffer image has the right resolution but is not painted with the correct resolution?


<img width="1440" alt="Bildschirmfoto 2020-04-15 um 07 57 13" src="https://user-images.githubusercontent.com/587976/79303404-1c948380-7eef-11ea-8490-b51688cc8523.png">

<img width="1440" alt="Bildschirmfoto 2020-04-15 um 07 57 18" src="https://user-images.githubusercontent.com/587976/79303408-1ef6dd80-7eef-11ea-992f-42e40a86c629.png">

<img width="1440" alt="Bildschirmfoto 2020-04-15 um 07 58 56" src="https://user-images.githubusercontent.com/587976/79303414-21593780-7eef-11ea-8162-2d53088f83d5.png">

**Comment by eselmeister** [comment]
@buchen Thanks for testing. We will have a look at this issue.

**Comment by lorenzgerber** [comment]
This Problem does not occur anymore hence the workaround has been removed: https://github.com/eclipse/swtchart/pull/412.
