### ISSUE TITLE
Mouse Wheel Zoom

### ISSUE THREAD

**Issue by eselmeister** [eclipse/swtchart#156]
The default behavior zooms in/out at the given mouse position in the chart. It's desirable to have additional functionality here. This should support

* Zoom X only
* Zoom Y only
* Zoom Y + start at 0 when doing an Y zoom

**Comment by yashTEF** [comment]
How are the above events supposed to be triggered by the user?,
Do we create new Event Processors in extensions.events
like-ZoomXEvent,ZoomYEvent etc.

**Comment by eselmeister** [comment]
Via the chart settings, events can be added. My solution is nearly ready. I'll try to commit and push the changes today. Afterwards, we can inspect the code together for explanation how it works.

**Comment by eselmeister** [comment]
It's quite complex to handle user range selection(s) and zoom events in a flexible and configurable way. Some changes in the API were required, but other projects should be not affected by these changes as:

* method(s) have been set to deprecated and redirect to the new methods
* defaults have been left untouched

The new range restriction handle user selection and mouse zoom events with different settings now.
