### ISSUE TITLE
Color changing for ISeries objects is not available

### ISSUE THREAD

**Issue by maxamly** [eclipse/swtchart#157]
[Here](http://www.swtchart.org/doc/index.html#Line_Series_Line_Color), in documentation there is a paragraph about changing line colors via setLineColor() method of ISeries object, but there is no such a method

**Comment by maxamly** [comment]
Okay, I found that casting ISeries to ILineSeries works

```java
ILineSeries series = (ILineSeries) chart.getSeriesSet().getSeries(seriesId);
```

**Comment by eselmeister** [comment]
Also have a look at the contained examples:

```
org.eclipse.swtchart.examples
org.eclipse.swtchart.extensions.examples
```

Either start the examples as an Eclipse application or run plain Java, e.g. the demo chart: 
`org.eclipse.swtchart.extensions.examples.charts.DemoChart`
