### ISSUE TITLE
Higher Level Nodes not clearly visible

### ISSUE THREAD

**Issue by himanshu-balasamanta** [eclipse/swtchart#201]
At higher levels of the Circular Charts, the colours tend to become dark and indistinguishable.
The angle covered by such nodes are usually small, making them hard to compare between themselves.
Thus, we must,
Add a listener that listens to clicks and recognises under which node of the circular chart does it lie, and render redrawn chart with that node as rootNode.
This will allow a clearer comparison between children of the same parent, and make them more distinguishable.

**Comment by eselmeister** [comment]
@Himanshu-Balasamanta Yep, that's a good idea.
