### ISSUE TITLE
Improve the Colouring of Circular Charts 

### ISSUE THREAD

**Issue by himanshu-balasamanta** [eclipse/swtchart#208]

**Comment by himanshu-balasamanta** [comment]
> **_Just because something works, doesn't mean it can't be improved_**

-Princess Shuri from _**'Black Panther'**_

**Comment by Utkarshn10** [comment]
@Himanshu-Balasamanta I want to contribute in this repo. Could you guide me how to proceed and where can I find the setting up guide for the repo. I have cloned the repo.

**Comment by himanshu-balasamanta** [comment]
https://accounts.eclipse.org/mailing-list/swtchart-dev
In this mailing list, scroll back one year, and check what all @eselmeister has written on how to run the project.

**Comment by Utkarshn10** [comment]
Thank you for replying!!!
