### ISSUE TITLE
Distance Measurement on X and Y axis

### ISSUE THREAD

**Issue by eselmeister** [eclipse/swtchart#229]
It would be great to measure distances in a chart, either a X or Y distance. The result should be displayed in the format of the visible axes. To achieve this, a combination of

- IBaseChartPaintListener
- MouseDown, MouseMove and MouseUp Event

could be used. It's not required to implement a solution now. The solution itself should be generic, so that it can be used in various situations, even when a reverse axis is used.

**Comment by Tanmay2510** [comment]
Hi, @eselmeister Sir I would like to contribute, can you suggest me ways to get started?

**Comment by eselmeister** [comment]
A demo has been implemented in ChemClipse:
https://github.com/eclipse/chemclipse/issues/572
