### ISSUE TITLE
Improve Commented Message in MultilLevelPieExample

### ISSUE THREAD

**Issue by Utkarshn10** [eclipse/swtchart#238]
Currently the file mentioned above contains commented message as shown. It can be improved to make it more contributer friendly.

![Capture](https://user-images.githubusercontent.com/58587256/106607873-cc73d400-6589-11eb-97e6-f4f42510bbdd.PNG)

**Comment by himanshu-balasamanta** [comment]
Kindly Close the issue now @eselmeister
