### ISSUE TITLE
Sortable Table Icon

### ISSUE THREAD

**Issue by Mailaender** [eclipse/swtchart#248]
https://github.com/eclipse/swtchart/issues/159 added an unlabeled checkbox that has to be discovered using the tooltip. Known iconography for this kind of feature does exist across applications and improves usability a tiny bit.

**Comment by eselmeister** [comment]
@Mailaender Have a look at some minor improvement I have appended to

- set the initial status image
- refresh the image after closing the settings editor
- set the list sort status after closing the settings
