### ISSUE TITLE
Eclipse 2021-06 and Java16

### ISSUE THREAD

**Issue by eselmeister** [eclipse/swtchart#252]
Create a test to run Eclipse SWTChart on the basis of the latest Eclipse IDE 2021-06 and the latest Java 16.

**Comment by eselmeister** [comment]
The latest Eclipse IDE and Java16 works fine. Some minor issues needs to be solved.
Findings:

- The bundle `org.eclipse.swtchart.export.extended` has been removed as Batik dependencies are needed. As `org.eclipse.swtchart.export` offers meanwhile a simple way to export to SVG, let's keep the overhead of the library small.
- Tycho 2.4.0-SNAPSHOT is needed (Java 16)
- https://github.com/eclipse/swtchart/issues/166 seems to be fixed (tested on Ubuntu 18.04)
- Currently, the feature and update site can't be build, see error log in the attachment

```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.swtchart.feature.feature.group 0.14.0.qualifier
[ERROR]   Missing requirement: org.eclipse.swtchart 0.14.0.qualifier requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=16))' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.swtchart.feature.feature.group 0.14.0.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.swtchart 0.0.0
[ERROR] 
[ERROR] See https://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: org.eclipse.swtchart:org.eclipse.swtchart.feature:0.14.0-SNAPSHOT @ /home/pwenig/www.lablicate.com/2021-06/ws/swtchart/org.eclipse.swtchart.feature/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

**Comment by Mailaender** [comment]
It seems this error occurred with the update to Java 8 previously https://bugs.eclipse.org/bugs/show_bug.cgi?id=530093 and had to be fixed in the Eclipse platform.

**Comment by Mailaender** [comment]
I vote against Java 16 as that will EOL in September. https://www.oracle.com/java/technologies/java-se-support-roadmap.html At least one release should be on the current LTS, then further upgrade steps can be undertaken.

**Comment by eselmeister** [comment]
I agree, we should first migrate to Java 11. If full Java 17 support is available next year, we could give the next LTS (Java 17) a try in 2022.

**Comment by eselmeister** [comment]
We use Tycho 2.7.0 now and Java 11. SWTChart works fine with GTK3 on Ubuntu 2021.10 with X11 and Wayland. For compatibility reasons with others projects, let's stay a while on Java 11.
