### ISSUE TITLE
Financial Charts?

### ISSUE THREAD

**Issue by nu11ptr** [eclipse/swtchart#260]
Any plans to add financial charts? OHLC? Candlesticks?

**Comment by eselmeister** [comment]
Yeah, why not. Please open separate issues for OHLC, Candlesticks and others.
See examples here:

https://github.com/eclipse/swtchart/issues/245 (Violin Plots)
https://github.com/eclipse/swtchart/issues/204 (Spider Charts)

Do you have knowledge and skills to implement you chart types?

**Comment by nu11ptr** [comment]
Possibly - it depends how much work it would entail. I've never used SWTChart, but am using JFreeChart atm, so it is more a "nice to have" atm

**Comment by nu11ptr** [comment]
I will open issues for the chart types

**Comment by eselmeister** [comment]
Great, probably we can encourage some Google Summer of Code students to create an implementation next year. If we've not done it ourselves before.
