### ISSUE TITLE
Wrong link to 0.13 release in project metadata

### ISSUE THREAD

**Issue by buchen** [eclipse/swtchart#269]
The [download section](https://projects.eclipse.org/projects/science.swtchart/downloads) in the project meta data *reads* 0.13.0 but in fact points to 0.12.0.

<img width="511" alt="Bildschirmfoto 2021-10-09 um 08 08 11" src="https://user-images.githubusercontent.com/587976/136646327-b91e15ff-3ded-4104-900c-3704a34bcd59.png">

**Comment by eselmeister** [comment]
Thanks for the hint. It has been fixed.
