### ISSUE TITLE
Make Axis Line optional

### ISSUE THREAD

**Issue by MatthewKhouzam** [eclipse/swtchart#274]
I am exploring for trace compass different ways to make the data easier to read

Here is an example chart with a pair of custom charts. A style that is becoming more popular now is a minimalist chart where the Y axis bar is invisible.
Example with Y Axis line:
![image](https://user-images.githubusercontent.com/419535/142291501-baf77d14-ff83-4652-a9c1-a5ccfbfce474.png)
And without
![image](https://user-images.githubusercontent.com/419535/142291162-4853d368-ba21-4609-b89a-ee21f8b39f94.png)
This image is an example of what I am looking for, and to get it, we just need to comment out one line. Do you have any API suggestions to make this make sense?

**Comment by eselmeister** [comment]
@MatthewKhouzam Am I right, you would like to disable drawing the black line of the Axis?

![Bildschirmfoto von 2021-11-19 06-33-27](https://user-images.githubusercontent.com/686671/142570852-40d61966-bbbd-4010-8f25-2a77758efc9b.png)

**Comment by MatthewKhouzam** [comment]
@eselmeister As usual, you are correct. It's trivial to do in the code, the API is the tricky part.

**Comment by eselmeister** [comment]
@MatthewKhouzam Let me inspect it. I'm pretty confident that extending the `IChartSettings` by an extra option will do the trick.

**Comment by eselmeister** [comment]
I found a solution. The code will be merged today.

**Comment by eselmeister** [comment]
@MatthewKhouzam Done :-)

The axis lines can be now activated/deactivated for each axis separately via the method `setDrawAxisLine(...)`, e.g.:

```
IChartSettings chartSettings = scrollableChart.getChartSettings();
chartSettings.getPrimaryAxisSettingsX().setDrawAxisLine(false);
scrollableChart.applySettings(chartSettings);
```

Have a look at the demo chart examples:
`org.eclipse.swtchart.extensions.examples.charts.DemoChart`

![Bildschirmfoto von 2021-11-21 11-01-14](https://user-images.githubusercontent.com/686671/142757891-c717b978-71ec-4ae5-a340-321500fc9700.png)

![Bildschirmfoto von 2021-11-21 11-01-26](https://user-images.githubusercontent.com/686671/142757895-43079b2d-e879-4be3-a7f4-9fab7747d76b.png)
