### ISSUE TITLE
Y-Axis both on left AND right?

### ISSUE THREAD

**Issue by harmanea** [eclipse/swtchart#283]
Is there a way to display the y-axis for a line chart synchronously both on the left and the right sides?

If not, would it be possible to add this option, e.g. something like `Position.BOTH`?

**Comment by eselmeister** [comment]
Setting the `Position.BOTH` is not possible. But you can simply add a secondary axis with a pass through value converter. Have a look here:
[SecondaryAxisChart.java](https://github.com/eclipse/swtchart/blob/develop/org.eclipse.swtchart.extensions.examples/src/org/eclipse/swtchart/extensions/examples/charts/SecondaryAxisChart.java)

**Comment by harmanea** [comment]
Thanks for the quick reply!

What do you mean by _pass through value converter_. I don't see it applied anywhere in the example.

**Comment by eselmeister** [comment]
In case of the example, a byte to kibibyte converter is used as the basic Y axis is given as byte:

```
ISecondaryAxisSettings secondaryAxisSettingsY = new SecondaryAxisSettings("KiB (kibibyte)", new ByteToKibibyteConverter());
```

If you'd like to mirror the axis,  just define a converter that returns the original value, so no multiplication/division is needed here.
