### ISSUE TITLE
Content of https://download.eclipse.org/swtchart/integration/REL-0.13.0/repository not signed

### ISSUE THREAD

**Issue by akurtakov** [eclipse/swtchart#293]
Linux Tools uses this repository to build against and contribute to simrel but it was found that content there is no longer signed.

**Comment by akurtakov** [comment]
It seems to be caused by https://github.com/eclipse/swtchart/commit/715a493ea5bc0ce32eba758c980b9b44bc7e9c9d

**Comment by akurtakov** [comment]
Is this one still needed?

**Comment by eselmeister** [comment]
We have reactivated the signing process. So the ticket can be closed.
