### ISSUE TITLE
Make getPixelCoordinate(...) a public method

### ISSUE THREAD

**Issue by eselmeister** [eclipse/swtchart#307]
It's not listed in the `IAxis` interface yet, hence using it could cause a `Discouraged access` warning.
`The method 'Axis.getPixelCoordinate(double, double, double)' is not API (restriction on required project 'org.eclipse.swtchart').`

**Comment by jackybian** [comment]
I pulled the latest changes from develop branch and created a new PR which contained my changes about  box plot.

**Comment by jackybian** [comment]
https://github.com/eclipse/swtchart/pull/308
