### ISSUE TITLE
Axis 0 value not displayed

### ISSUE THREAD

**Issue by MatthewKhouzam** [eclipse/swtchart#353]
This is a bug I introduced. https://github.com/eclipse/swtchart/commit/2d0865e339b85c6006a10a22f119b770b263302e

When the value of the y axis is 0, we don't display anything since `double diff = Math.abs((value - tickLabelValues.get(i)) / value);` means `(0.0-0.0)/0.0 < 0.1`

A- Sorry

B- I will try to patch it in the near future.

**Comment by eselmeister** [comment]
@MatthewKhouzam Thanks for reporting. I will also have a look at it.

**Comment by iloveeclipse** [comment]
Could be a duplicate of https://github.com/eclipse/swtchart/issues/375?

**Comment by eselmeister** [comment]
Right, thanks. It's a duplicate of #375.
