### ISSUE TITLE
axis tick labels are not properly shown in some cases

### ISSUE THREAD

**Issue by yoshitaka1008** [eclipse/swtchart#375]
I have seen two cases where axis tick labels are not properly shown.

**case 1**: when setting axis range containing zero, axis tick label "0" is not shown.

actual:
![actual_1](https://github.com/eclipse/swtchart/assets/11504728/19bd1dce-8b97-4132-9bee-d66489d3831d)
expected (before the fix for [#124](https://github.com/eclipse/swtchart/issues/214)):
![expected_1](https://github.com/eclipse/swtchart/assets/11504728/410a3ee4-47a2-4d0f-a812-af7633ba6d4e)

Note: the issue is reproducible with Test1.java in [test.zip](https://github.com/eclipse/swtchart/files/13373883/test.zip)

**case 2**: when setting axis tick label format, duplicated tick labels are shown.

actual:
![actual_2](https://github.com/eclipse/swtchart/assets/11504728/0a8e36da-9e55-4d86-a1ba-9fb96e644896)

expected (before the fix for [#124](https://github.com/eclipse/swtchart/issues/214)):
![expected_2](https://github.com/eclipse/swtchart/assets/11504728/6935cbc3-5e17-445c-a1ea-b0cafc7feb68)

Note: the issue is reproducible with Test2.java in [test.zip](https://github.com/eclipse/swtchart/files/13373883/test.zip)

**Comment by yoshitaka1008** [comment]
Analysis and possible solution:
- With the fix of #214, the logic to determine whether axis tick label is a major one to display was changed.
- I assume the intention of fix was to accept a certain diff between actual tick value and value of tick label display so that tick labels can be shown even when value of tick label display is rounded with axis tick format using IAxisTick.setFormat().
- The diff was evaluated by abs((actualTickValue - valueOfTickLabelDisplay / actualTickValue).
- But the issue of this approach is that, when actualTickValue becomes larger (e.g. showing range of 10000 to 10000.3), the diff is evaluated smaller.
- A possible better approach would be to evaluate the diff based on pixels in display.

**Comment by yoshitaka1008** [comment]
Hi @MatthewKhouzam , does the patch [375.patch](https://github.com/eclipse/swtchart/files/13374336/375.patch) work in your case?

**Comment by yoshitaka1008** [comment]
patch with tests: [375_fix_with_tests.patch](https://github.com/eclipse/swtchart/files/13375839/375_fix_with_tests.patch)

**Comment by eselmeister** [comment]
@yoshitaka1008 Thanks for your patches. I will also test them.

**Comment by MatthewKhouzam** [comment]
This is fine here. Thanks for checking!

**Comment by ghost** [comment]
There is a jar file with the patch?

**Comment by eselmeister** [comment]
@yoshitaka1008 @MatthewKhouzam Thanks for your feedback.
@VictorRojasGIT Wait for the next run of [https://ci.eclipse.org/swtchart/job/build/job/develop/](https://ci.eclipse.org/swtchart/job/build/job/develop). Jars are available after successful build on:
[https://download.eclipse.org/swtchart/integration/develop/repository](https://download.eclipse.org/swtchart/integration/develop/repository) or build it yourself via Maven/Tycho.

**Comment by eselmeister** [comment]
The "0" label issue was already solved.

![Screenshot from 2024-09-02 19-34-14](https://github.com/user-attachments/assets/a130edd2-ddc8-4a81-8533-ec7e4d186ff2)

The "duplicated tick labels" was introduced on purpose. But it's true that it might be confusing if no value is displayed at all.

**Comment by eselmeister** [comment]
![Screenshot from 2024-09-02 19-38-05](https://github.com/user-attachments/assets/44003a6a-8438-4f07-b11e-66b3fcff3cec)
![Screenshot from 2024-09-02 19-38-27](https://github.com/user-attachments/assets/e3edc108-5f6a-4e1b-b651-6898753ee57d)

**Comment by eselmeister** [comment]
The user defines the tick decimal format. It's almost impossible to deduct a more fine grained decimal format as the decimal format may have been set on purposes. To display that it's not a chart defect, three dots are set instead of hiding the label.
