### ISSUE TITLE
org.eclipse.swtchart.Constants  class has been removed.

### ISSUE THREAD

**Issue by raghucssit** [eclipse/swtchart#384]
We are consuming the org.eclipse.swtchart.Constants.
This class has been removed as a part of https://github.com/eclipse/swtchart/issues/329.
We just want to know  rtionale for removing public class.

**Comment by eselmeister** [comment]
To have a better control of the consumed Colors and Fonts, the values from `Constants` have been moved to:
`org.eclipse.swtchart.Resources`
