### ISSUE TITLE
INFO/QUESTION: When is the next release planned for swtchart ?

### ISSUE THREAD

**Issue by raghucssit** [eclipse/swtchart#390]
Sorry for creating it as an issue. I will close it once the INFO is available.
There is no discussion tab for this repo.
We are interested in latest release of swtchart to use it in our application.
Please let us know when a new release will be available.

**Comment by eselmeister** [comment]
Currently, we are trying to include vectorgraphics2d into SWTChart. This could take another 2-3 months. The next release is planned for autumn 2024.

**Comment by raghucssit** [comment]
@eselmeister Thank you so much for the info..
I am closing it as I got the info..
