### ISSUE TITLE
Create a formater profile to use for the project

### ISSUE THREAD

**Issue by laeubi** [eclipse/swtchart#4]
We should provide CodeFormater Templates for Eclipse that can be used to format the source-code of SWT Chart in a consitent way.

**Comment by laeubi** [comment]
Or we can simply use the Eclipse Formatter profile, but it should be documented somewhere what formatter to use.

**Comment by eselmeister** [comment]
Yep, good idea. I'll take care of it.

**Comment by eselmeister** [comment]
Done.
