### ISSUE TITLE
[question] is new release planned?

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse/swtchart#410]
As I don't see a "discussion" section on the project, asking via this issue.
Do you plan to release new version soon?
We are particularly interested in getting fix for https://github.com/eclipse/swtchart/issues/375 in the new release.

**Comment by eselmeister** [comment]
A new release is planned as soon as the vectorgraphics2d code is integrated. We're waiting for the code review:
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/15837

**Comment by iloveeclipse** [comment]
Thanks, looks like the IP review stalled.

**Comment by eselmeister** [comment]
Yep, I will take care of it this. I was on holidays the last weeks, hence I hoped things have been reviewed already.

**Comment by eselmeister** [comment]
#375 has been also addressed.

**Comment by eselmeister** [comment]
@iloveeclipse The PDF issue is solved :-)
https://github.com/eclipse/swtchart/issues/417

I will prepare the official SWTChart v1.0 release within the next weeks. Probably, I need your help to setup the deployment to Maven Central. I already tried it, but it seems to be failed and I'm a bit lost how to fix it.

**Comment by iloveeclipse** [comment]
Hi, any update on a new release?

**Comment by eselmeister** [comment]
It's in preparation.

**Comment by eselmeister** [comment]
Created the release branch:
https://github.com/eclipse/swtchart/tree/REL-1.0.0

**Comment by eselmeister** [comment]
A release review has been requested. The release of version 1.0.0 is scheduled for 2024-11-29:
https://projects.eclipse.org/projects/science.swtchart

**Comment by buchen** [comment]
Any news?

**Comment by eselmeister** [comment]
Yes, the release review has concluded successfully:
https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/835

I will prepare the official binaries approx. by tomorrow.

**Comment by eselmeister** [comment]
https://github.com/eclipse/swtchart/releases/tag/REL-1.0.0
