### ISSUE TITLE
Use target platform for Tycho build

### ISSUE THREAD

**Issue by buchen** [eclipse/swtchart#58]
Tycho can also use a target platform definition to resolve dependencies. From my point of view, the advantage is that the very same target definition is used during the build as well as when developing inside the Eclipse IDE.

If you are interested, I can prepare a change that a) updates Tycho to the latest version and b) introduces the target platform file that is used during the build and inside the IDE. Let me know.

**Comment by laeubi** [comment]
I think this is a good idea.

**Comment by laeubi** [comment]
I think contributions are always welcome, just make sure you have signed ECA and sign off your commit otherwise it will reject to merge.

**Comment by laeubi** [comment]
Since we are currently facing issues regarding to update, I'll provide a patch that enables this soon.
