### ISSUE TITLE
swtchart as a Gradle dependency

### ISSUE THREAD

**Issue by harmanea** [eclipse/swtchart#64]
Hello,
I'm building a standalone SWT application with Gradle and I can't figure out how to add this wonderful library as a dependency. From what I can tell, swtchart isn't published to any Maven repo. Usually with GitHub this is also possible using JitPack or the Gradle gitRepository function but neither works here. Are there any plans to enable this?

**Comment by kerner1000** [comment]
Hi @harmanea , currently, Maven/ Gradle Support is not available. Please feel free to submit a PR.

**Comment by buchen** [comment]
I believe the ask from @harmanea is to publish SWTChart to Maven Central. That requires signing the build with a GPG key, uploading it to a Sonatype repository, and releasing it. In particular, one must own the namespace (org.eclipse.swtchart). IMHO, this is something the project owners must do, that is not a PR on the code base.

BTW, I have published the "legacy" SWTChart 0.10.0 version to my own Maven repository here: https://github.com/buchen/maven-repo If you are able to add repositories to your build besides Maven central, feel free to use it.

**Comment by eselmeister** [comment]
I'm not familiar with Gradle.
@harmanea: Feel free to add a Gradle script to the bundle org.eclipse.swtchart.cbi.

Regarding the signing of the jars, have a look at this ticket:
https://github.com/eclipse/swtchart/issues/66

**Comment by harmanea** [comment]
Sorry for a late reply.

What I'm looking for is a repository from which Gradle can download the packaged library and add it to my project's build path. Maven central or any other repository would be the ideal solution but I don't think I can do that on my own. See the [Maven guide](https://maven.apache.org/repository/guide-central-repository-upload.html).

The legacy library that @buchen offered is enough for me now (even though I was hoping to be able to experiment with the extensions) so feel free to close this.

**Comment by meinctutw** [comment]
+1 I also use gradle and want to pull swtchart with it.

**Comment by eselmeister** [comment]
I'm not familiar using Gradle. Anyway, please provide a PR and a description how to use it. After testing, I will merge it.Am 04.01.2020 22:46 schrieb meinctutw <notifications@github.com>:+1 I also use gradle and want to pull swtchart with it.

**Comment by Mailaender** [comment]
See https://wiki.eclipse.org/Platform-releng/Publish_To_Maven_Central
