### ISSUE TITLE
Provide an Updatesite

### ISSUE THREAD

**Issue by laeubi** [eclipse/swtchart#65]
The Updatesite is already generated as part of the buil, but currently not uploaded to an official location.
If Eclipse itself does not offer support, we might can use github-pages for this.

**Comment by eselmeister** [comment]
I'll take care of it at the next Eclipse Hackathon:
https://wiki.eclipse.org/Hackathon_Hamburg_2019_Sept

**Comment by eselmeister** [comment]
The update site of the latest release 0.7.0 is available here:
https://download.eclipse.org/swtchart/0.7.0/update
