### ISSUE TITLE
IAxisTick does not draw dates in Brazil timezone

### ISSUE THREAD

**Issue by jimmyd-be** [eclipse/swtchart#73]
```
IAxisTick xTick = chart.getAxisSet().getXAxis(0).getTick();
DateFormat format = new SimpleDateFormat("y/M/d");
xTick.setFormat(format);
```

We have an application with SWT chart. Now we are deploying the application to Brazil. But we found out that users in Brazil does not see the chart details.

The chart in all timezones (except Brazil) looks like:
![image](https://user-images.githubusercontent.com/34766203/63690913-1fcaea00-c80e-11e9-916d-0ce90f9f428a.png)

In Brazil timezone it looks like:
![image](https://user-images.githubusercontent.com/34766203/63690977-4c7f0180-c80e-11e9-9f99-c95ac53a9d12.png)

The above screenshots above are created with the same data and source but with another timezone configured.

**Comment by eselmeister** [comment]
Could you provide a demo data set and the code of the chart, so that we are able to reproduce the issue?
