### ISSUE TITLE
StepChart as a new chart type

### ISSUE THREAD

**Issue by eselmeister** [eclipse/swtchart#82]
Currently, the following chart types are available:

- BarChart
- ScatterChart
- LineChart

Support for a new chart type "ScatterChart" shall be added. It is principally available already. When adding series, the following setting needs to be activated:

- lineSeriesSettings.setEnableStep(true);

This could be done by the "ScatterChart" automatically when adding new data "addSeriesData(...)".

**Comment by yashTEF** [comment]
Do we add a new SeriesType like SeriesType.STEP in the SeriesType enum
e.g.-
`ILineSeries lineSeries = (ILineSeries)chart.getSeriesSet().createSeries(SeriesType.STEP, "step series");`
further we proceed as
```
if(type==SeriesType.STEP)
{
series=new LineSeries(chart,"Id");

series.enableStep(true);
}
```

**Comment by eselmeister** [comment]
https://github.com/eclipse/swtchart/commit/c6f16628782fc9cdf86c3826e1b08156b0a2759e
