### ISSUE TITLE
Release version should be newer than 0.10

### ISSUE THREAD

**Issue by akurtakov** [eclipse/swtchart#83]
I see that Eclipse swtchart version released is 0.7 but latest sourceforge version is 0.10 . It would make sense to use bigger version than the sourceforge version to make it clear that it's newer.

**Comment by eselmeister** [comment]
Hi Alex,yes, we know that this might be confusing. We followed the Eclipse guideline to start with a version < 1, commonly used 0.7.Probably, we should use version 0.11 or 0.12 for the next official release.Am 06.12.2019 21:58 schrieb Alexander Kurtakov <notifications@github.com>:I see that Eclipse swtchart version released is 0.7 but latest sourceforge version is 0.10 . It would make sense to use bigger version than the sourceforge version to make it clear that it's newer.

**Comment by eselmeister** [comment]
OK, we try to use version 0.12 for the next release.

**Comment by akurtakov** [comment]
Nice. 
P.S. I've seen https://download.eclipse.org/swtchart/0.8.1/ but no announcement nor release record. Is this some kind of snapshot?
P.S.1 I strongly advice projects to make latest p2 url e.g. https://download.eclipse.org/swtchart/latest which other projects can refer to if they want and pick latest swtchart version always.

**Comment by eselmeister** [comment]
@laeubi Do you know where 0.8.1 comes from? We only have one official release at the moment: 0.7.0. Each release has do be reviewed by the Eclipse IP team.

https://projects.eclipse.org/projects/science.swtchart/downloads

**Comment by eselmeister** [comment]
Eclipse SWTChart is also linked to Eclipse Babel now:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=559143

As @akurtakov has requested a version > 0.10, the next release version will be 0.12.

**Comment by laeubi** [comment]
All these are not releases but Branch-Builds, each branch gets build and deployed there so we can consume and test them in downstream builds. 0.8.1 is the current "stable" build for chemclipse without API changes so we probably never release 0.8.1 at any time.

**Comment by eselmeister** [comment]
https://projects.eclipse.org/projects/science.swtchart/releases/0.12.0
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21754

**Comment by eselmeister** [comment]
A new release has been requested.

**Comment by eselmeister** [comment]
The release review has been concluded successful:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=560752

**Comment by eselmeister** [comment]
https://download.eclipse.org/swtchart/REL-0.12.0/repository/
