### ISSUE TITLE
Chart is flipped vertically when saved as image on Mac OS

### ISSUE THREAD

**Issue by fbuloup** [eclipse/swtchart#86]
On Mac OS (this is what I have experienced), when you choose to save chart as image, this image is flipped vertically. It must be flipped again to retrieve a nice chart image. I have changed the **save** method in **chart.java** to solve the problem (hint from http://www.java2s.com/Tutorial/Java/0300__SWT-2D-Graphics/WriteanImagetoaPNGfile.htm). Here is the changed source code :

```java
/**
* Saves to file with given format.
* 
* @param filename
*            the file name
* @param format
*            the format (SWT.IMAGE_*). The supported formats depend on OS.
*/
public void save(String filename, int format) {
        Image image = new Image(Display.getDefault(), getBounds());
        GC gc = new GC(image);
	print(gc);
	gc.dispose();
	ImageData imageData = image.getImageData();
	
        ///CHANGES START HERE<<<<<<--------
	String osName = System.getProperty("os.name").toLowerCase();
	boolean isMacOs = osName.startsWith("mac os x");
	if (isMacOs) {
		//Flip image vertically when Mac Os 
		int bytesPerPixel = imageData.bytesPerLine / imageData.width;
		int destBytesPerLine = imageData.width * bytesPerPixel;
		byte[] newData = new byte[imageData.data.length];
		for (int srcY = 0; srcY < imageData.height; srcY++) {
			for (int srcX = 0; srcX < imageData.width; srcX++) {
				int destX = 0, destY = 0, destIndex = 0, srcIndex = 0;
				destX = srcX;
				destY = imageData.height - srcY - 1;
				destIndex = (destY * destBytesPerLine) + (destX * bytesPerPixel);
				srcIndex = (srcY * imageData.bytesPerLine) + (srcX * bytesPerPixel);
				System.arraycopy(imageData.data, srcIndex, newData, destIndex, bytesPerPixel);
			}
		}
		// destBytesPerLine is used as scanlinePad to ensure that no padding is required
	        imageData = new ImageData(imageData.width, imageData.height, imageData.depth, 
                imageData.palette, destBytesPerLine, newData);
	}
	////CHANGES END HERE<<<<<<--------
    
	ImageLoader loader = new ImageLoader();
	loader.data = new ImageData[]{imageData};
	loader.save(filename, format);
	image.dispose();
}
```

Do you think it could be useful to include it in SWTChart ?

**Comment by eselmeister** [comment]
Thanks for the feedback. We will inspect this issue.

**Comment by buchen** [comment]
@eselmeister Does the Transform work for you on macOS? I tried to re-apply this to my code base but for me the Transform has no effect (the code by @fbuloup works)

And: Does it make sense to change the ```Chart#save``` method?

**Comment by eselmeister** [comment]
I don't have a macOS at hand. The transform code works fine to flip images under Linux. So, I assumed that it also works in reverse to flip the image under macOS to normal status.How does it look now under macOS?Could you try to play/debug the transform operation on your mac?Am 15.12.2019 10:40 schrieb Andreas Buchen <notifications@github.com>:@eselmeister Does the Transform work for you on macOS? I tried to re-apply this to my code base but for me the Transform has no effect (the code by @fbuloup works)
And: Does it make sense to change the Chart#save method?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
Am 15.12.2019 10:40 schrieb Andreas Buchen <notifications@github.com>:@eselmeister Does the Transform work for you on macOS? I tried to re-apply this to my code base but for me the Transform has no effect (the code by @fbuloup works)
And: Does it make sense to change the Chart#save method?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
Am 15.12.2019 10:40 schrieb Andreas Buchen <notifications@github.com>:@eselmeister Does the Transform work for you on macOS? I tried to re-apply this to my code base but for me the Transform has no effect (the code by @fbuloup works)
And: Does it make sense to change the Chart#save method?

**Comment by buchen** [comment]
I can check on the swtchart code base later this week.

**Comment by eselmeister** [comment]
That would be great. I prefer to use the Transform method as it's easier to use and transform should do the trick. As you said, the code of @fbuloup works, but we should try to rely on system functions whenever possible. Moreover, I would have to check that the code of @fbuloup has not been copied and pasted from somewhere else.

**Comment by fbuloup** [comment]
As I mentioned in my original post, I took the above code example from  this link :

http://www.java2s.com/Tutorial/Java/0300__SWT-2D-Graphics/WriteanImagetoaPNGfile.htm

But I think there is a much more simple solution which probably works on all platforms.
**Just create the graphical context on current chart instance and copy the entire area into the new created image**. Then you can get the image data from it. Finally it appears that with this solution, you don't need any geometrical transformation nor image data manipulation. I've tested this on MacOS and it works fine for jpeg and bmp image formats.

Here is the small code :

```java
...
Image image = new Image(Display.getDefault(), theChart.getBounds());
GC gc = new GC(theChart);
gc.copyArea(image, 0, 0);
gc.dispose();
ImageData imageData = image.getImageData();
image.dispose();
...
```

**Comment by buchen** [comment]
@eselmeister - I had the chance to test the code now. I ran the "org.eclipse.swtchart.examples" projects with "Run as Eclipse application" and then selected one of the top right charts, right-click and saved as PNG or JPEG. The image is unfortunately still rotated. It is not clear to me what goes wrong. The *Transform* is setup, but it seems to me that the SWT code overrides it with some other Transform.

BTW, the target platform definition seems to be incomplete as one class was complaining about missing *org.apache.batik* dependencies - see below. I was using the target platform form the "o.e.s.targetplatform" project.
<img width="516" alt="Bildschirmfoto 2019-12-27 um 20 50 54" src="https://user-images.githubusercontent.com/587976/71531133-9b889080-28ed-11ea-8d06-5d7a6c4e66d4.png">

@fbuloup - thanks for the code snippets. Works fine for me.

**Comment by buchen** [comment]
@fbuloup upon further inspection: it works for JPEG, but I see some artifacts when saving the chart as PNG file. I see straight diagonal lines across the whole image - compare the JPEG and PNG versions. 🤔 Any ideas?

**JPEG**
![Performance-Diagramm_(Dashboard)](https://user-images.githubusercontent.com/587976/71531550-785ee080-28ef-11ea-8175-d2c716c29850.jpeg)

**PNG**
![Performance-Diagramm_(Dashboard)](https://user-images.githubusercontent.com/587976/71531549-77c64a00-28ef-11ea-93ba-7b0abcaabd0e.png)

**Comment by fbuloup** [comment]
Sorry but I've not been able to reproduce this strange diagonal line for PNG files ! It's probably  a problem related to SWT version.

I've investigated in SWT OS X java code and seen that there is a strange applied transformation in the **print** method of the **control** class :

```java
...
public boolean print (GC gc) {
	checkWidget ();
	if (gc == null) error (SWT.ERROR_NULL_ARGUMENT);
	if (gc.isDisposed ()) error (SWT.ERROR_INVALID_ARGUMENT);

	NSGraphicsContext.static_saveGraphicsState();
	NSGraphicsContext.setCurrentContext(gc.handle);
	NSAffineTransform transform = NSAffineTransform.transform (); // *****
	transform.translateXBy (0, view.bounds().height); // *****
	transform.scaleXBy (1, -1); // *****
	transform.concat (); // *****
	view.displayRectIgnoringOpacity(view.bounds(), gc.handle);
	NSGraphicsContext.static_restoreGraphicsState();
	return true;
}
...
```

When you comment lines that I've marked with stars, the image is no longer flipped vertically ! Do you have any idea on the utility of these transformations ?  🤔

Nevertheless and after a couple of hours, I've been able to modify the  **ImageSupplier** class in order to export chart properly to BMP, PNG or JPEG image. Here is the resulting java code :

```java
...
public class ImageSupplier {

	public void saveImage(ImageData imageData, String fileName, int format) {
		ImageLoader imageLoader = new ImageLoader();
		imageLoader.data = new ImageData[]{imageData};
		imageLoader.save(fileName, format);
	}

	public ImageData getImageData(BaseChart baseChart) {
		// Force to redraw chart immediately to be sure that any 
		// Shell dialog won't be a part of the copied image  
		baseChart.redraw();
		baseChart.update();
		// Create the image provider
		ImageDataProvider imageDataProvider = new ImageDataProvider() {
			@Override
			public ImageData getImageData(int zoom) {
				if(zoom != 100) return null;
				int width = baseChart.getSize().x;
				int height = baseChart.getSize().y;
				PaletteData palette = new PaletteData(0xFF , 0xFF00 , 0xFF0000);
			    ImageData imageData = new ImageData(width, height, 24, palette);
				return imageData;
			}
		};
		// Copy chart into the image
		Image image = new Image(baseChart.getDisplay(), imageDataProvider);	
		GC gc = new GC(baseChart);
		gc.copyArea(image, 0, 0);
		// Retrieve image data
		ImageData imageData = image.getImageData(100);
		gc.dispose();
		image.dispose();
		return imageData;
	}

	/// No longer necessary
//	private boolean isMacOS() {
//		return (getOperatingSystem().indexOf("mac") >= 0);
//	}
//
//	private String getOperatingSystem() {
//		return System.getProperty("os.name").toLowerCase();
//	}
	
	
}
```

I've made some tests with MacOS 10.14.6 and windows 7. Windows was running with VirtualBox. For now,  I'm using SWT 4763 on Mac OSX and 4924 on Windows. Perhaps this strange diagonal line is related to SWT releases differences... Here are two exported images :

PNG Result :
![PNG File](https://user-images.githubusercontent.com/8910494/71556909-8ec78200-2a3e-11ea-80b9-e9ff1f4a31bc.png)

JPEG result :
![JPEG File](https://user-images.githubusercontent.com/8910494/71556910-8ec78200-2a3e-11ea-96c9-36cc95b34602.jpeg)

It's also working for BMP format, but not supported by GitHub.

BTW, in order to run **org.eclipse.swtchart.extensions.examples**, it has been necessary to update target platform with all these bundles :


**org.apache.batik.constants_1.9.1.v20180227-1645.jar
org.apache.batik.css_1.9.1.v20181015-1528.jar
org.apache.batik.dom_1.9.1.v20190730-1743.jar
org.apache.batik.ext.awt_1.9.1.v20190730-1743.jar
org.apache.batik.i18n_1.9.1.v20180227-1645.jar
org.apache.batik.svggen_1.9.1.v20190730-1743.jar
org.apache.batik.util_1.9.1.v20180703-1553.jar
org.apache.batik.xml_1.9.1.v20190730-1743.jar
org.apache.commons.io_2.6.0.v20190123-2029.jar
org.apache.xalan_2.7.1.v201005080400.jar
org.apache.xml.serializer_2.7.1.v201005080400.jar
org.apache.xmlgraphics_2.3.0.v20190515-0436.jar**

But there is still a problem on OS X because the exported image size is twice the chart size !
It appears that the latest SWT release is 4930 and I will try to update to this version hoping everything will be solved ! I will give a feedback ASAP.

**Comment by laeubi** [comment]
@fbuloup do you think you can supply your changes on a fork of this repository and open a PR? This would make things a lot easier (commenting, seeing diffs, possibly merging), let me know if you need any guidance.

BTW if there is a bug in SWT/Cocoa it would be best to report it here https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Platform

**Comment by laeubi** [comment]
@buchen I created #91 for that, the problem is that the examples are not part of the build and the target platform only contains necessary bundles for building the bundles, so eclipse might get confused.

**Comment by fbuloup** [comment]
@laeubi : i’ve created a bugzilla n°558678 yesterday. Will fork, commit little changes and open a PR

**Comment by fbuloup** [comment]
It seems that a check has failed for the PR : 
eclipsefdn/eca — The author(s) of the pull request is not covered by necessary...
