### ISSUE TITLE
SWT Chart Should Use Internationalization

### ISSUE THREAD

**Issue by fbuloup** [eclipse/swtchart#97]
SWT Chart plugins should use Internationalization.

I will provide a PR to propose changes in order to implement these changes

**Comment by eselmeister** [comment]
I have added a comment.
Otherwise it looks good.

@laeubi Do you have any comments?

**Comment by laeubi** [comment]
I wonder if there are more labels that needs translation.

**Comment by fbuloup** [comment]
Yes there are : other menu items and some message on dialog box.
I will try to do a commit before tomorow
